Paggio.html do
  script type: "text/javascript", src: "script.js"
  link rel: "stylesheet", href: "style.css"
  h1 { "Hello world from Justicar" }
  hr
  h2.paggio do
    'Hello world from Paggio!'
  end
  p.paggio do
    "This part was generated by Paggio in HTML :)"
  end
end
