Paggio.html do
  script type: "text/javascript", src: "script.js"
  link rel: "stylesheet", href: "style.css"
  link rel: 'icon', type: 'image/x-icon', href: 'favicon.ico'
  img.justicar(src: '/justicar.png', alt: 'Justicar', height: '400px')
  h1 { "Hello world from Justicar" }
  hr
  h2.paggio do
    'Hello world from Paggio!'
  end
  p.paggio do
    "This part was generated by Paggio in HTML :)"
  end
end
