require 'opal'
require 'native'
require 'promise'
require 'browser/setup/full'

$document.ready do
  DOM do
    h2.opal do
      "Hello World from Opal!"
    end
    p.opal {"This part was generated by Opal from Javascript (:"}
  end.append_to($document.body)
end
